spring.application.name=application
#spring.mongodb.uri=mongodb://mongo:27017/chatdb

spring.mongodb.uri=mongodb://localhost:27017/chatdb
telegram_bot_token=${TELEGRAM_BOT_TOKEN}
telegram_chat_id=${TELEGRAM_CHAT_ID}